### ISSUE TITLE
ARMv7 32-bit instructions

### ISSUE THREAD

**Issue by ghost** [troyfontaine/armhf-alpinelinux#5]
I am trying to compile code on this docker that makes use of 32-bit instructions `dmb ish` and friends (targeting only armv7):
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0489c/CIHGHHIE.html

Compiler is giving `error: invalid operand for instruction` at usage of `dmb ish`.

I am setting appropriate arch CFlags `-march=armvv7-a`, which fixed lots of other errors I was getting before.

Are extended ARMv7-32-bit-only instructions supported by this docker? Is there anything we can do to enable those?

Thanks!

**Comment by troyfontaine** [comment]
Hi @kasper3 ,

This image is using the stock ARM image made by the maintainers of Alpine Linux-I just toss in a QEMU binary to allow it to run on x86/x86-64.

Are you running the image on an ARM board or using a conventional x86-64 machine?

**Comment by ghost** [comment]
Hi @troyfontaine,

I am using x86-64 machine. I made a simple test:

```c
#include <stdio.h>
int main()
{
   asm volatile ("dmb ish" : : : "memory");
   return 0;
}
```

compiled with `clang test.c -o test.exe -march=armv7-a`, and it worked (without `-march=armv7-a`, it gives the error). It seems like something is wrong with CMake configuration of the project I am trying to build (something is overwriting CFlag). I will check, but the docker is good as is. 😃 

Thanks for building this useful docker.
